### ISSUE TITLE
Could not find a version that satisfies the requirement magic-cli (from versions: ) No matching distribution found for magic-cli

### ISSUE THREAD

**Issue by magicpia** [magic-network/magic-cli#14]
Hello!Sorry to contact you but I have a problem on installing "magic-cli" as a client,can you help me to install it.I have no experience on using Ubuntu.I have follow the installing instruction but I have a problem.The problem is on line that I must install "pip3 install",I have a message like that: "Could not find a version that satisfies the requirement magic-cli (from versions: )
No matching distribution found for magic-cli".Can you give me all instruction to install it please.

Created on behalf of herizonirinanjiva@gmail.com

**Comment by Sanjih** [comment]
Hello.Here is the screenshoot of my problem.Can you help me please.
![magic](https://user-images.githubusercontent.com/48612771/54585546-64ff1a80-4a2b-11e9-94b7-8c94f8107f9d.png)

**Comment by magicpia** [comment]
@Sanjih Can you try running `pip3 install .` instead of the last command you ran above `pip3 install magic-cli` 

Here is the documentation section for reference: https://magic-network.github.io/magic-cli/quick-start/installing-cli.html

Let us know if you still run into any issues!

**Comment by magicpia** [comment]
Hi @Sanjih were you able to install the CLI? We can help walk through as well if needed. Just let us know. Thanks!

**Comment by Sanjih** [comment]
Hello.Sorry but not yet.I really have same problem to install it.Can you
help me please?

Le jeu. 28 mars 2019 à 23:22, Pia Opulencia <notifications@github.com> a
écrit :

**Comment by magicpia** [comment]
From a separate email thread, @Sanjih was able to install the CLI and is now working on getting a Gateway Agent stood up to be able to connect to a network node.

**Comment by DomAmato** [comment]
@magicpia can we close this issue then or are there fixes we need to add to the code base to prevent this issue?
